Repository archerysec/archerysec, pull requests merged in 2021-04, with the labels that each got.

#463 #461 Fix openvas findings are not reflecting after scan completion
  scanners/scanner_plugin/network_scanner/openvas_plugin.py
Labels: bugfix

#465 Fix issue of djangorestframework-jwt deprecated
  archeryapi/views.py
  archerysecurity/settings/base.py
  archerysecurity/urls.py
  requirements.txt
Labels: bugfix

#466 Arachni Plugin Fix and Requirements Fix
  PyArachniapi.py
  archerysettings/migrations/0004_auto_20210407_1148.py
  archerysettings/models.py
  archerysettings/save_settings.py
  docker-compose.yml
  requirements.txt
  webscanners/arachniscanner/views.py
  webscanners/templates/arachniscanner/arachni_settings_form.html
  webscanners/templates/setting.html
  webscanners/web_views.py
Labels: enhancement

#468 fix CVE-2021-30459 and CVE-2020-28463
  requirements.txt
Labels: dependencies

#469 updated setup.sh file that fix macOS installation issue
  setup.sh
Labels: bugfix
